#!/bin/bash
# Check Truepool.io Chia Pool v1.1
# Ensure your Chia farm is online and farming to the pool
# By Robbie Ferguson // https://nemslinux.com/

# Depends: jq curl

if [ -z "$1" ] ; then
    echo "UNKNOWN - missing Launcher ID"
    exit 3
fi

if ! ( command -v jq >/dev/null ) ; then
    echo "UNKNOWN - jq command not found"
    exit 3
fi

if ! ( command -v curl >/dev/null ) ; then
    echo "UNKNOWN - curl command not found"
    exit 3
fi

launcher=$1
api="https://truepool.io/api/v1.0/launcher/"
resp=$(curl -s "${api}${launcher}/")
points=$(echo $resp | jq -r '.points')
points_pplns=$(echo $resp | jq -r '.points_pplns')
difficulty=$(echo $resp | jq -r '.difficulty')
detail=$(echo $resp | jq -r '.detail')
share=$(echo $resp | jq -r '.share_pplns')
share_percent=$(echo "scale=2;${share}*100" | bc)
name=$(echo $resp | jq -r '.name')

# jq uses 'null' instead of 0, so correct it
if [[ $points == "null" ]]; then
  points=0
fi
if [[ $points_pplns == "null" ]]; then
  points_pplns=0
fi
if [[ $difficulty == "null" ]]; then
  difficulty=0
fi

if [[ $points_pplns > 0 ]]; then
  if [[ $points > 0 ]]; then
    o_pplns=$(printf "%'d" $points_pplns)
    o_share=$(printf "%.4f" $share_percent)
    echo "OK - Points: $o_pplns (24 Hrs) / Share: ${o_share}% / Diff: $difficulty | $name"
    exit 0
  else
    echo "WARNING - Farm appears online, but is not generating points."
    exit 1
  fi
elif [[ $detail != 'null' ]]; then
  echo "CRITICAL - $detail"
  exit 2
else
  echo "CRITICAL - Farm appears to be offline."
  exit 2
fi
