#!/bin/bash

  # Some platforms have the package named differently
  if [[ ! -e /usr/bin/chromium-browser ]]; then
    if [[ -e /usr/bin/chromium ]]; then
      ln -s /usr/bin/chromium /usr/bin/chromium-browser
    fi
  fi

  # Install promised-io so nems-speedtest can find needed modules
  npm install request-promise --cli

  # Setup a cache file for NEMS TV Dashboard
  touch /var/log/nems/speedtest-fast.log
  chmod 666 /var/log/nems/speedtest-fast.log

